### ISSUE TITLE
About the code block in markdown in blog.

### ISSUE THREAD

**Issue by Tivility** [Tivility/tivility.github.io#11]
The c++ code in markdown could not get it's wrap correctly especially in comments. It also not have highlight and line number as well. I fix them as fellow. 

### fix line number and highlight as [this issue](https://github.com/jekyll/jekyll/issues/4619#issuecomment-191267346).   
Change the code in `_config.yml` file. 

```yml
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
```

as fellow

```yml
markdown: kramdown
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
```

### fix the wrap as [this issue](https://github.com/Huxpro/huxpro.github.io/issues/210#issuecomment-364958609)
Change the code in `/css/syntax.css` 

```css
.highlight pre code * {
white-space: nowrap; // this sets all children inside to nowrap
}
```

as fellow

```css
.highlight pre code * {
white-space: pre; // this sets all children inside to nowrap
}
```

maybe next time I'll change the code block theme.
